server:
  port: ${SERVER_PORT:10418}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:nhnacademy-be12-trillion/config-repo.git
          default-label: main
          private-key: file:///config/.ssh/id_ed25519
          ignore-local-ssh-settings: true
#            -----BEGIN OPENSSH PRIVATE KEY-----
#            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
#            QyNTUxOQAAACCeiYf0h2rOx9cMVvQxIEElmky7B0HPVdXkPc+QmNxPTAAAAJguB6mZLgep
#            mQAAAAtzc2gtZWQyNTUxOQAAACCeiYf0h2rOx9cMVvQxIEElmky7B0HPVdXkPc+QmNxPTA
#            AAAEDSQQg6O5j+24M7RlJxiMJdC8s7A7KinzAA5BgOH4jvY56Jh/SHas7H1wxW9DEgQSWa
#            TLsHQc9V1eQ9z5CY3E9MAAAAE3NlcnJvdDI0QGdpdGh1Yi5jb20BAg==
#            -----END OPENSSH PRIVATE KEY-----
#          host-key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
#          host-key-algorithm: ssh-ed25519


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}