name: config-service package

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY_OWNER: nhnacademy-be12-trillion
  REGISTRY: ghcr.io
  IMAGE_NAME: config-server
  JAVA_VERSION: 21
  DEPLOY_DIR: ~/msa-project

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'


      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: GitHub Packages 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ env.REGISTRY_OWNER }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: 이미지 태그 세팅
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_OWNER }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=raw,value=latest,enable=true

      - name: 도커 이미지 빌드 & 푸시
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: 파일 전송 및 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            SERVICE_NAME="config-server"
            echo "SSH 접속 및 디렉토리 이동..."
            mkdir -p ${{ env.DEPLOY_DIR }}
            cd ${{ env.DEPLOY_DIR }}
            
            export CONFIG_SERVER_PRIVATE_KEY="${{ secrets.CONFIG_SERVER_PRIVATE_KEY }}"

            echo "Docker Registry 로그인"
            echo ${{secrets.GHCR_TOKEN}} | docker login ${{ env.REGISTRY }} -u ${{ env.REGISTRY_OWNER }} --password-stdin

            echo "최신 Config Server 이미지 Pull 및 서비스 재시작..."
            docker-compose pull ${SERVICE_NAME}
            docker-compose up -d --force-recreate ${SERVICE_NAME}

            echo "Docker Registry 로그아웃..."
            docker logout ${{ env.REGISTRY }}